package:
    name: pygpyg
    version: 1.0.20230210

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pandas         >=0.2.0
    run:
        - pandas         >=0.2.0
        
about:
    home: https://github.com/gityoav/pyg
    license: GNU