package:
    name: pyg
    version: 1.0.6

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg_npy        >=0.0.7
        - pyg_base       >=0.0.19
        - pyg_mongo      >=0.0.13
        - pyg_timeseries >=0.0.19
        - pyg_bond       >=0.0.3
        - pyg_encoders   >=0.0.3
        - pyg_cell       >=0.0.3
        - pyg_sql        >=0.0.3
    run:
        - pyg_npy        >=0.0.7
        - pyg_base       >=0.0.19
        - pyg_mongo      >=0.0.13
        - pyg_timeseries >=0.0.19
        - pyg_bond       >=0.0.3
        - pyg_encoders   >=0.0.3
        - pyg_cell       >=0.0.3
        - pyg_sql        >=0.0.3
        
about:
    home: https://github.com/gityoav/pyg
    license: GNU