package:
    name: pyg
    version: 1.0.1

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy         >=1.19.1
        - scipy         >=1.5.0
        - pandas        >=1.1.0
        - jsonpickle    >=1.2
        - fastparquet   >=0.4.1
        - motor         >=2.3.0
        - pymongo       >=3.11.0
        - bottleneck    >=1.3.2
        - xarray        >=0.19.0
    run:
        - numpy         >=1.19.1
        - scipy         >=1.5.0
        - pandas        >=1.1.0
        - jsonpickle    >=1.2
        - fastparquet   >=0.4.1
        - motor         >=2.3.0
        - pymongo       >=3.11.0
        - bottleneck    >=1.3.2
        - xarray        >=0.19.0
        
about:
    home: https://github.com/gityoav/pyg
    license: GNU